### ISSUE TITLE
Missing 'docs' folder in this repo.

### ISSUE THREAD

**Issue by SalvorinFex** [freetronics/KitTen#1]
I read this in the readme.md

"The "docs" folder within this repository includes a handy copy of the schematic in PDF format, images of the pcb, and our Getting Started guide that ships with each board."

However, I do not see a "docs" folder.

**Comment by jonoxer** [comment]
This project was originally derived from the "Eleven" board project, so the README was copied over and never updated. Sorry about that. I've just edited the README to remove the reference to those non-existent files, and also pushed other updates to the board itself.
